apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: messaging-app
  name: messaging-app
spec:
  type: NodePort
  ports:
  - port: 5173
    protocol: TCP
    name: http
  selector:
    io.kompose.service: messaging-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: messaging-app
  name: messaging-app
spec:
  selector:
    matchLabels:
      io.kompose.service: messaging-app
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: messaging-app
    spec:
      containers:
      - image: messaging-app
        name: messaging-app
        imagePullPolicy: Always
        ports:
        - containerPort: 5173
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: messaging-app-ingress
spec:
  rules:
  - host: messaging-app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: messaging-app
            port:
              number: 5173
