apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: messaging-app
  name: messaging-app
spec:
  type: NodePort
  ports:
  - port: 5173
    protocol: TCP
    name: http
  selector:
    io.kompose.service: messaging-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: messaging-app
  name: messaging-app
spec:
  selector:
    matchLabels:
      io.kompose.service: messaging-app
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: messaging-app
    spec:
      containers:
      - image: messaging_app
        name: messaging-app
        imagePullPolicy: Always
        ports:
        - containerPort: 5173
        resources: {}
      restartPolicy: Always
status: {}