apiVersion: v1
kind: Service
metadata:
  name: messaging-app
spec:
  type: NodePort
  ports:
  - port: 5173
    protocol: TCP
    name: http
  selector:
    app: messaging-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app
spec:
  selector:
    matchLabels:
      app: messaging-app
  replicas: 1
  template:
    metadata:
      labels:
        app: messaging-app
    spec:
      containers:
      - image: messaging-app
        name: messaging-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5173
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: messaging-app-ingress
spec:
  rules:
  - host: messaging-app.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: messaging-app
            port:
              number: 5173
