name: Build, Test and Push
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: npm install
    - run: npm run lint
    - run: npm run test
    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and run docker containers
      run: |
        docker-compose up -d && \
          docker ps && sleep 5
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        push: true
        tags: dasha12678/messaging-app:latest
    - name: Install GitLeaks
      run: |
        curl -sSfL https://raw.githubusercontent.com/zricethezav/gitleaks/master/install.sh | sudo bash -s -- -b /usr/local/bin v7.6.1
    - name: Run GitLeaks
      run: gitleaks --repo-path . --report-format=csv --report=gitleaks-report.csv