name: Build, Test and Push
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Run lint tests
      run: npm run lint
    - name: Run unit tests
      run: npm run test
    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and run docker containers
      run: |
        docker-compose up -d && \
          docker ps && sleep 5
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        push: true
        tags: dasha12678/messaging-app:latest
